version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ubiety
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ubiety_iot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ubiety"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ubiety:password@db:5432/ubiety_iot
      - API_KEY=supersecretkey123
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: